version: '2'
services:
  mongodb:
    image: docker.io/bitnami/mongodb
    volumes:
      - '../mongodb_data:/bitnami/mongodb'
    environment:
      - MONGODB_USERNAME=easy_budgeting_mongo
      - MONGODB_DATABASE=easy_budgeting_mongo_db
      - MONGODB_PASSWORD=3b_m0ng0
    ports: 
      - 27017:27017
  parse:
    image: docker.io/bitnami/parse
    ports:
      - '1337:1337'
    volumes:
      - '../parse_data:/bitnami/parse'
    depends_on:
      - mongodb
    environment:
      - PARSE_DATABASE_HOST=mongodb
      - PARSE_DATABASE_PORT_NUMBER=27017
      - PARSE_DATABASE_USER=easy_budgeting_mongo
      - PARSE_DATABASE_NAME=easy_budgeting_mongo_db
      - PARSE_DATABASE_PASSWORD=3b_m0ng0
      - PARSE_ENABLE_CLOUD_CODE=yes
      - PARSE_APP_ID=EasyBudgetingServer
      - PARSE_MASTER_KEY=3b_m4st3r_k3y
      - PARSE_APP_NAME=EasyBudgeting
    volumes:
      - '../parse_data:/bitnami'
      - './cloud/main.js:/cloud/main.js'
  parse-dashboard:
    image: docker.io/bitnami/parse-dashboard
    ports:
      - '4040:4040'
    environment: 
      - PARSE_DASHBOARD_PARSE_APP_ID=EasyBudgetingServer
      - PARSE_DASHBOARD_PARSE_APP_NAME=EasyBudgeting
      - PARSE_DASHBOARD_PARSE_MASTER_KEY=3b_m4st3r_k3y
      - PARSE_DASHBOARD_USERNAME=admin
      - PARSE_DASHBOARD_PASSWORD=admin
    volumes:
      - '../parse_dashboard_data:/bitnami'
    depends_on:
      - parse
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local